# Config file for automatic testing at travis-ci.org

language: python
install: pip install tox
script: tox

env:
  - TOXENV=py27-django18
  - TOXENV=py34-django18
  - TOXENV=py27-django19
  - TOXENV=py34-django19
  - TOXENV=py35-django19
  - TOXENV=py27-django110
  - TOXENV=py34-django110
  - TOXENV=py35-django110
  - TOXENV=py27-django-master
  - TOXENV=py35-django-master

matrix:
    allow_failures:
        # Django master is allowed to fail
        - env: TOXENV=py27-django-master
        - env: TOXENV=py35-django-master

# See pylibmc's .travis.yml if a lot more configuration is needed
services:
  - memcached
